//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyhocsinhcap3
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEMSO
    {
        public int MaHS { get; set; }
        public int MaPC { get; set; }
        public Nullable<int> Diem15s_1 { get; set; }
        public Nullable<int> Diem15s_2 { get; set; }
        public Nullable<int> Diem15s_3 { get; set; }
        public Nullable<int> Diem15s_4 { get; set; }
        public Nullable<int> Diem1tiet_1 { get; set; }
        public Nullable<int> Diem1tiet_2 { get; set; }
        public Nullable<int> Diem1tiet_3 { get; set; }
        public Nullable<int> Diemgiuaki { get; set; }
        public Nullable<int> Diemcuoiki { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    
        public virtual HOCSINH HOCSINH { get; set; }
        public virtual PHANCONG PHANCONG { get; set; }
    }
}
