//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyhocsinhcap3
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOPHOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOPHOC()
        {
            this.PHANCONGs = new HashSet<PHANCONG>();
            this.XEPLOPs = new HashSet<XEPLOP>();
        }
    
        public int MaLH { get; set; }
        public string TenLH { get; set; }
        public Nullable<int> MaNH { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> GVCN { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    
        public virtual GIAOVIEN GIAOVIEN { get; set; }
        public virtual KHOIHOC KHOIHOC { get; set; }
        public virtual NAMHOC NAMHOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANCONG> PHANCONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XEPLOP> XEPLOPs { get; set; }
    }
}
