//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyhocsinhcap3
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANCONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHANCONG()
        {
            this.DIEMSOes = new HashSet<DIEMSO>();
        }
    
        public int MaPC { get; set; }
        public Nullable<int> MaGV { get; set; }
        public Nullable<int> MaLH { get; set; }
        public Nullable<int> MaHK { get; set; }
        public Nullable<int> MaMH { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIEMSO> DIEMSOes { get; set; }
        public virtual GIAOVIEN GIAOVIEN { get; set; }
        public virtual HOCKY HOCKY { get; set; }
        public virtual LOPHOC LOPHOC { get; set; }
        public virtual MONHOC MONHOC { get; set; }
    }
}
