//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyhocsinhcap3
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANNHAN
    {
        public int MaTN { get; set; }
        public int MaHS { get; set; }
        public string TenTN { get; set; }
        public string CongViec { get; set; }
        public string SDT { get; set; }
        public string QuanHe { get; set; }
    
        public virtual HOCSINH HOCSINH { get; set; }
    }
}
