//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyhocsinhcap3
{
    using System;
    using System.Collections.Generic;
    
    public partial class XEPLOP
    {
        public int MaXL { get; set; }
        public Nullable<int> MaHS { get; set; }
        public Nullable<int> MaLH { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    
        public virtual HOCSINH HOCSINH { get; set; }
        public virtual LOPHOC LOPHOC { get; set; }
    }
}
